name: Generate Keystore
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v \
            -keystore jokerich.jks \
            -alias jokerich \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "JokerDownloader2024" \
            -keypass "JokerDownloader2024" \
            -dname "CN=Jokerich, OU=JokerDownloader, O=Jokerich, L=Cairo, ST=Cairo, C=EG"
          
          echo "===== Keystore created ====="
          keytool -list -v -keystore jokerich.jks -storepass "JokerDownloader2024"

      - name: Convert to Base64
        run: |
          base64 jokerich.jks > keystore.txt
          echo "===== BASE64 START ====="
          cat keystore.txt
          echo "===== BASE64 END ====="

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: jokerich-keystore
          path: |
            jokerich.jks
            keystore.txt
